org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.compiler.runViaBuildToolsApi=true

KOTLIN_VERSION=2.4.10
GROUP=io.github.sagernet
VERSION_NAME=0.1.0-SNAPSHOT

POM_URL=https://github.com/SagerNet/libghostty-android
POM_LICENSE_NAME=MIT
POM_LICENSE_URL=https://opensource.org/license/mit
POM_DEVELOPER_ID=nekohasekai
POM_DEVELOPER_NAME=nekohasekai
POM_SCM_URL=https://github.com/SagerNet/libghostty-android
POM_SCM_CONNECTION=scm:git:https://github.com/SagerNet/libghostty-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/SagerNet/libghostty-android.git
